modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
clientSideOnly=true
[[mods]]
authors="Cutjjen"
modId="nvvisionvulkanbridge"
version="0.7.26"
displayName="NVVision Addon Forge"
displayTest="IGNORE_ALL_VERSION"
# Category: optimization
description="Client-side CPU visual controls. No driver switching or network channels."
[[dependencies.nvvisionvulkanbridge]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"
[[dependencies.nvvisionvulkanbridge]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"
[[dependencies.nvvisionvulkanbridge]]
modId="nvvisionboost"
mandatory=true
versionRange="[0.7.14,0.8)"
ordering="AFTER"
side="CLIENT"


