modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="nvvisionboost"
version="0.8.16"
displayName="NVVision Boost NeoForge"
authors="Cutjjen"
displayTest="IGNORE_ALL_VERSION"
description='''Client-side graphics optimization by Cutjjen: hardware presets, spatial upscaling, dynamic resolution and local visual controls. Open settings with F8 or Minecraft Options.'''
[[dependencies.nvvisionboost]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
[[dependencies.nvvisionboost]]
modId="neoforge"
type="required"
versionRange="[21.1.251,21.2)"
ordering="NONE"
side="CLIENT"
[[mixins]]
config="nvvisionboost.mixins.json"
[[dependencies.nvvisionboost]]
modId="sodium"
type="required"
versionRange="[0.8.13,0.9)"
ordering="AFTER"
side="CLIENT"
[[dependencies.nvvisionboost]]
modId="iris"
type="optional"
versionRange="[1.8,1.9)"
ordering="AFTER"
side="CLIENT"




